# First include the real Makefile
include Makefile

# Then, define the other targets needed by Automake Makefiles
.PHONY: dvi pdf ps info html check tags ctags distclean maintainer-clean \
	mostlyclean installdirs uninstall data exec distdir

dvi pdf ps info html check tags ctags distclean installdirs uninstall \
data exec distdir:

mostlyclean maintainer-clean: clean