/* Public interface file for random.c.

   random.c provides a high quality pseudo random number generator
   that is much better than the system library function in most cases.

   The PRNG must be seeded before it can be used. prng_seed(time(0))
   is a simple way to seed it. This is the equivalent prototype to the
   system call srandom().

   Call prng_next() to get the next number generated by the PRNG. This
   is the equivalent prototype to the system call random().
*/

#ifndef _RANDOM_H
#define _RANDOM_H

#include <stdint.h>

/* Seeds the PRNG. */
void prng_seed(uint32_t seed);

/* Gets the next 32-bit integer from the PRNG. */
uint32_t prng_next();

/* Gets a float in the uniform distribution over [0,1).  */
float prng_uniform();

#endif /* _RANDOM_H */
